name: Build

on:
  push:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: |
        docker run termux/termux-docker:x86_64 bash -c "pkg upgrade && pkg install -y git && git clone https://github.com/denoland/deno && pkg install -y rust && cargo b --release"
        
